### PR TITLE
Pull syntax

### PR DESCRIPTION
**Pull request by cawasser**
convert several data sources to using datascript "pull syntax" to simplify the queries

### CODE REVIEW

**Review by gpierce3 — APPROVED** [review]
built/ran dev/uber/docker.  Looks good.
One thing, if you pick a beam service and attach to heatmap instead of globe, heatmap looks weird.  Like a single very narrow bar in a bar chart.  Not sure if due to data, or heatmap widget or what.

**Comment by cawasser** [comment]
> built/ran dev/uber/docker.  Looks good.
> One thing, if you pick a beam service and attach to heatmap instead of globe, heatmap looks weird.  Like a single very narrow bar in a bar chart.  Not sure if due to data, or heatmap widget or what

This is because heat-map registers for :data-format/lat-lon-n and lat-lon-e but doesn't actually support them. I removed that meta-data. Also updated the data-source and widget to pass the category labels from the server. Thanks for checking this.

**Review by austinpaine — APPROVED** [review]

**Review by chadarm — APPROVED** [review]

**Comment by chadarm** [comment]
Might want to add a markdown file as a resource for datamonic/data interactions like this.

**Comment by cawasser** [comment]
> Might want to add a markdown file as a resource for datamonic/data interactions like this.

Good point. Adding a doc-file.

**Review by austinpaine — APPROVED** [review]
Readme update was a good call, well written explanation

**Pull request merged**
