### PR TITLE
Mapupdate

### PR DESCRIPTION
**Pull request by gpierce3**
Australia map now shows cities.
Added some city display to continent map.
Australia map and continent map show same Australian cities.
Added png of Australia map for widget selector.

Issue:  'Panning' the continent map is strange.  I think that is an issue with Highcharts, not us.

### CODE REVIEW

**Review by bfhub — APPROVED** [review]
verified the new updates, all works well. just running uberjar throws an exception, missing database
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: services)

**Comment by cawasser** [comment]
bfhub, not sure why you would have an issue  with the uberjar. I'm not seeing it at all. the plain uberjar should be able to access the vanilla_db in your working folder

**Review by cawasser — CHANGES_REQUESTED** [review]
please make :zoom property be "xy" for both maps. see https://github.com/cawasser/vanilla/blob/64d363746b786956033272f04dc189a2bac5dbd2/src/cljs/vanilla/widgets/australia_map.cljs#L29 for one example. with that change we can approve and merge

**Review by bfhub — COMMENTED** [review]
@cawasser I verified the uberjar on my Mac machine as well, and got the same exception. what I did was running lein uberjar, and then testing it using java -jar target/uberjar/vanilla.jar command. I see the exception, and also after connecting to the application, localhost:5000, the login fails. I will make a new branch and pulls again, and will test it again. will keep you posted.

**Review by cawasser — APPROVED** [review]

**Review by cawasser — APPROVED** [review]

**Pull request merged**
