### PR TITLE
Jira149

### PR DESCRIPTION
**Pull request by gpierce3**
This code was pulled before the new vanilla db changes.
I did NOT push my db.
Added a continent map as a 'base' map.  Added a country map (Australia).
Also created a make-map namespace, since map stuff slightly different from chart code.

Issues:   Australia map does not yet display cities.  Need to make image for the data/widget picker.

### CODE REVIEW

**Review by bfhub — COMMENTED** [review]
Can someone else check and see if the log in is an option when starting the application in chrome on a window machine?  I only see the Add button.

**Review by bfhub — COMMENTED** [review]
please ignore my last review. I missed George's comment on the review request. I am revising the changes now. thanks.

**Review by bfhub — COMMENTED** [review]
Please change the "Australia Data" to "Australia Map", this makes it similar to what we have in widget_defs:

-      ["14000" "australia-map-service" "Australia Data"
+      ["14000" "australia-map-service" "Australia Map"

after updating the vanilla_db, the Australia map will be listed in menu.

**Comment by cawasser** [comment]
0.3.5-SNAPSHOT. Database has been updated to include the 2 new data services. Looks good.

**Pull request merged**
