### PR TITLE
Ww timeline carousel

### PR DESCRIPTION
**Pull request by cawasser**
additions for [WorldWind](https://github.com/worldwindearth/worldwind-react-globe), [Timeline](https://github.com/guiqui/react-timeline-gantt), and [Carousel](https://github.com/express-labs/pure-react-carousel
).
- also includes update(s) for [area-fix](https://github.com/cawasser/vanilla/pull/50)

### CODE REVIEW

**Review by gpierce3 — COMMENTED** [review]
dev mode:

splash screen is huge.  Can only see top of 'Black'.
splash screen 'scrolls down' as widgets added.
carousel added, button of the widget overlaps name of widget below it.

uberjar:

Same as above.
Had to create a vanilla db from vanilla default by hand to resolve some issues.
The following occured once (was unable to duplicate):
Added spectrum trace widget.  a partial 'ghost' of it appeared next to the WW widget. deleting spectrum widget eliminated it
A line in the carousel widget extended beyond the right side of the widget off the screen.

Docker:
Was unable to build docker image.  SHA512 error caused failure.

**Comment by cawasser** [comment]
1. yes the splash image is really big, but if it isn’t then it tiles and looks really bad. I’m willing to consider alternative implementations (I just made it the background-image of the body-tag.) In general, we need a better (one one at all) way to make the grid fill the user’s entire display, but I don’t know enough JS or CSS to make this work

2. yes, the spash image scrolls, again due to how it’s implemented (as we add widgets that <div> gets taller, pushing the body down.)

3. I was able to get then uberjar built, after deleting the vanilla_db and just letting the server generate a new one

4. I got a few npm warnings (please fund, you are out of date, etc), but the docker container DID built and it DID deploy.

5. the dockerized server ran, but when I added a WorldWind widget it didn’t show the terminals or beam, really anything from the excel file. Turns out the “Demo.xslx” is NOT included in the uberjar, but 2 xslx files we AREN’T USING are! Not sure what’s going on there. (the one for the other demo is also NOT included, but it shouldn’t be anyway). The uberjar did have this data because its running from the dev folder, so the excel file(s) are in the expected place.

**Comment by cawasser** [comment]
actually, I was wrong, all the xslx files are in the uberjar (need to remember that for our "special branch builds"), but they seem not to be found by the server during execution

**Comment by gpierce3** [comment]
> 1. yes the splash image is really big, but if it isn’t then it tiles and looks really bad. I’m willing to consider alternative implementations (I just made it the background-image of the body-tag.) In general, we need a better (one one at all) way to make the grid fill the user’s entire display, but I don’t know enough JS or CSS to make this work

Ah.  I thought it was more like wallpaper and was concerned it was not adjusting to screen/window resolution/size.

> 2. yes, the spash image scrolls, again due to how it’s implemented (as we add widgets that  gets taller, pushing the body down.)

Makes sense due to 1. above.

> 3. I was able to get then uberjar built, after deleting the vanilla_db and just letting the server generate a new one

This does not work for me. A zero length db file is created, and trying to sign up fails.

> 4. I got a few npm warnings (please fund, you are out of date, etc), but the docker container DID built and it DID deploy.

I pulled latest and can now build/run docker.  also get a few npm warning.

> 5. the dockerized server ran, but when I added a WorldWind widget it didn’t show the terminals or beam, really anything from the excel file. Turns out the “Demo.xslx” is NOT included in the uberjar, but 2 xslx files we AREN’T USING are! Not sure what’s going on there. (the one for the other demo is also NOT included, but it shouldn’t be anyway). The uberjar did have this data because its running from the dev folder, so the excel file(s) are in the expected place.

Works okay after pulling latest based on your commits last night.

**Review by chadarm — APPROVED** [review]
It took me a minute to get used to seeing vanilla code again, seems like we're making a lot of headway. 

Everything looks good and works on uberjar and docker. The splash image is a good touch, gets our name out there.

**Comment by austinpaine** [comment]
The html changes for the splash background image look great, nicely done!

**Review by gpierce3 — APPROVED** [review]

**Review by chadarm — APPROVED** [review]
The new changes with the splash and version tag look great. I also really appreciate the upgraded comments in add-widget namespace.

Seems good to go!

**Pull request merged**
